openapi: 3.0.0
info:
  title: APIs Definition
  description: |
      # OpenAPI specification for SAC106
      **API's** supported by Integration can be found here.
  contact:
    name: API Support
    email: support@xyz.com
  version: 0.0.1
servers:
  - url: https://dev.api.ed.ac.uk/students/api/v1/
    description: Development server
components:
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      in: header
      name: Authorization
      description: 'Use this header to pass the token for authorization'
security:
  - AuthorizationHeader: []
paths:
  /student/uun/{uun}:
    get:
     summary: Find a student by uun
     description: To get the student details for the given uun
     parameters:
      - name: uun
        in: path
        required: true
        schema:
          type: string
     responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  studentCode:
                    type: string
                  personIdentifier:
                    type: string
                  admissionsAgencyIdentifier: 
                    type: string

        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /subject/code/{code}:
    get:
      summary: Find a subject by code
      description: To get the subject details for the given subject code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  subjectCode:
                    type: string
                  subjectName:
                    type: string
                  inUse: 
                    type: boolean
                  programmeAreaCode:
                    type: string
                  programmeAreaName:
                    type: string
                  subjectGroupCode:
                    type: string
                  subjectGroupName:
                    type: string
                  costCentreCode:
                    type: string
                  costCentreName:
                    type: string
                  externalSubjectCode:
                    type: string
                  externalSubjectName:
                   type: string
                  roomSpecific:
                   type: string
                  atasSensitiveResearch:
                   type: boolean
                  atasSensitiveTaught:
                   type: boolean
                  level6Unit:
                   type: string
                  jacsCodeReview:
                   type: string
                  costCentreReview:
                   type: string
                  sfcFundingGroupOnSub:
                   type: string
                  type:
                   type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /published-programme/code/{code}:
    get:
      summary: Find a IPP by code
      description: To get the published programme details for the given IPP code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ipProgrammeCode:
                    type: string
                  sourceOfData:
                    type: string
                  pubProgSourceCode: 
                    type: string
                  title :
                    type: string
                  departmentCode :
                    type: string
                  keywords:
                    type: string
                  subjectAreas:
                    type: string
                  programmeOfStudyCode : 
                    type: string
                  routeCode :
                    type: string
                  process :
                    type: string
                  publish:
                    type: string
                  status:
                    type: string
                  standardLetterGroupCode: 
                    type: string
                  standardResponseLetter :
                    type: string
                  personnelCode :
                    type: string
                  coursePublishingSchedule:
                    type: string
                  noOfReferences:
                    type: string
                  publishOnlyNextAcademicYear : 
                    type: string
                  publishedStartDates :
                    type: string
                  sacsNotes :
                    type: string
                  facultyCode: 
                    type: string
                  inUse :
                    type: string
                  feeAttached :
                    type: string
                  createdDate:
                    type: string
                    format: date
                  createdTime:
                    type: string
                    format: date-time
                  createdByCode : 
                    type: string
                  updatedDate :
                    type: string
                    format: date
                  updatedTime :
                    type: string
                    format: date-time
                  updatedByCode :
                    type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /published-prog-inst/code/{code}/seqn/{seqn}:
    get:
      summary: Find a IPO by code
      description: To get the published programme instance details for the given IPO code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
        - name: seqn
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ipProgrammeCode:
                    type: string
                  sequenceNumber:
                    type: string
                  applyURL: 
                    type: string
                  sourceOfData :
                    type: string
                  pubProgSourceCode :
                    type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /drps-files/code/{code}/type/{type}:
     get:
      summary: Find a drps-file-catalogue by code or type
      description: To get the drps file catalogue details for the given code
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
        - name: type
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  sessionYear:
                    type: string
                  type:
                    type: string
                  code: 
                    type: string
                  filePath:
                    type: string
                  fileName:
                    type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
