openapi: 3.0.0
info:
  title: APIs Definition
  description: |
      # OpenAPI specification for SAC106
      **API's** supported by Integration can be found here.
  contact:
    name: API Support
    email: support@xyz.com
  version: 0.0.1
servers:
  - url: https://dev.api.ed.ac.uk/students/api/v1/
    description: Development server
components:
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      in: header
      name: Authorization
      description: 'Use this header to pass the token for authorization'
security:
  - AuthorizationHeader: []
paths:
  /student/uun/{uun}:
    get:
      parameters:
        - name: uun
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  studentCode:
                    type: string
                  personIdentifier:
                    type: string
                  admissionsAgencyIdentifier: 
                    type: string

        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /subject/code/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  subjectCode:
                    type: string
                  subjectName:
                    type: string
                  inUse: 
                    type: boolean
                  programmeAreaCode:
                    type: string
                  programmeAreaName:
                    type: string
                  subjectGroupCode:
                    type: string
                  subjectGroupName:
                    type: string
                  costCentreCode:
                    type: string
                  costCentreName:
                    type: string
                  externalSubjectCode:
                    type: string
                  externalSubjectName:
                   type: string
                  roomSpecific:
                   type: string
                  atasSensitiveResearch:
                   type: boolean
                  atasSensitiveTaught:
                   type: boolean
                  level6Unit:
                   type: string
                  jacsCodeReview:
                   type: string
                  costCentreReview:
                   type: string
                  sfcFundingGroupOnSub:
                   type: string
                  type:
                   type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
  /published-programme/code/{code}:
    get:
      parameters:
        - name: code
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
          content:
            application/json:
              schema:
                type: object
                properties:
                  ipProgrammeCode:
                    type: string
                  sourceOfData:
                    type: string
                  pubProgSourceCode: 
                    type: string
                  title :
                    type: string
                  departmentCode :
                    type: string
        '401':
         description: Unauthorized
        '403':
         description: Forbidden
        '404':
         description: Record not found 
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
