openapi: 3.0.0
info:
  title: APIs Definition
  description: |
     OpenAPI specification for SAC106
  contact:
    name: API Support
    email: support@xyz.com
  version: 0.0.1
servers:
  - url: https://dev.api.ed.ac.uk/students/api/v1/
    description: Development server
components:
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      in: header
      name: Authorization
      description: 'Use this header to pass the token for authorization'
security:
  - AuthorizationHeader: []
paths:
  /student/uun/{uun}:
    get:
      parameters:
        - name: uun
          in: path
          required: true
          schema:
            type: string
        - name: Authorization
          in: header
          required: true
          schema:
            type: string
      responses:
        '200':
          description: ok
      security:
        - AuthorizationHeader: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
