openapi: 3.0.0
info:
  title: APIs Definition
  description: |
     OpenAPI specification for SAC106
  contact:
    name: API Support
    email: support@xyz.com
  version: 0.0.1
servers:
  - url: https://dev.api.ed.ac.uk/students/api/v1/
    description: Development server
components:
  securitySchemes:
    AuthorizationHeader:
      type: apiKey
      in: header
      name: Authorization
      description: 'Use this header to pass the token for authorization'
security:
  - AuthorizationHeader: []
paths:
  /student/uun/{uun}:
    get:
    summary: GET a specific student
    description: Returns the student information 
      parameters:
        - name: uun
          in: path
          required: true
          schema:
            type: string
          example: S9999999
      responses:
        '200':
          description: ok
          content:
           application/json:
             schema:
               type: array
               items:
                 type: object
                 properties:
                   studentCode:
                     type: string
                   personIdentifier:
                     type: string
                   admissionsAgencyIdentifier:
                     type: string
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Record not found
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
