openapi: 3.0.0
info:
  title: APIs Definition
  description: |
     OpenAPI specification for SAC106
  contact:
    name: API Support
    email: support@xyz.com
  version: 0.0.1
servers:
  - url: https://www-dev.star.euclid.ed.ac.uk/public/urd/sits.urd/run/SIW_RWS
    description: Development server
paths:
 /student/uun/{uun}:
    get:
      parameters:
        - name: uun
          in: path
          required: true
          style: simple
          explode: false
          schema:
            type: string
            format: string
        - name: Authorization
          in: header
          required: true
          style: simple
          explode: false
          schema:
            type: string
      responses:
        '200':
          description: ok
      security:
        - default: []
      x-auth-type: Application & Application User
      x-throttling-tier: Unlimited
      x-throttling-limit:
        requestCount: -1
        unit: MINUTE
